// src/app/api/exports/restore/route.ts
// =============================================================================
// MehmanGhar Financial OS — Restore from JSON Backup
//
// POST — accepts a JSON backup produced by GET /api/exports?model=all and
//        upserts all records back into the database.
//
// SuperAdmin only.
//
// Safety rules:
//   - All operations are upserts (createMany with skipDuplicates=true, then
//     updateMany for changed fields). Existing records are never deleted.
//   - If a table's data is malformed or missing, that table is skipped and
//     the error is reported. Other tables continue restoring.
//   - Decimal string values from the backup are converted back to numbers.
//   - Returns a summary of how many records were processed per table.
// =============================================================================

import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/db";
import { requireRole, RoleRequiredError } from "@/lib/permissions";
import { regenReports } from "@/lib/regenReports";

interface RestoreResult {
  table: string;
  processed: number;
  error?: string;
}

interface RestoreResponse {
  results: RestoreResult[];
  total_processed: number;
}

interface ErrorResponse {
  error: string;
}

export async function POST(
  request: NextRequest
): Promise<NextResponse<RestoreResponse | ErrorResponse>> {
  const role = request.headers.get("x-user-role") ?? "";

  try {
    requireRole(role, ["SuperAdmin"]);
  } catch (err) {
    if (err instanceof RoleRequiredError) {
      return NextResponse.json({ error: err.message }, { status: 403 });
    }
    return NextResponse.json({ error: "An unexpected error occurred." }, { status: 500 });
  }

  let body: Record<string, unknown>;
  try {
    body = (await request.json()) as Record<string, unknown>;
  } catch {
    return NextResponse.json({ error: "Invalid JSON body. Expected a backup JSON file." }, { status: 400 });
  }

  // Verify this looks like a valid backup
  if (!body._meta || typeof body._meta !== "object") {
    return NextResponse.json(
      { error: "Invalid backup format. Missing _meta field. Use a backup file generated by this platform." },
      { status: 422 }
    );
  }

  const results: RestoreResult[] = [];

  // ---------------------------------------------------------------------------
  // Properties
  // ---------------------------------------------------------------------------
  if (Array.isArray(body.properties)) {
    try {
      const rows = (body.properties as Array<Record<string, unknown>>).filter(
        (r) => typeof r.id === "string"
      );
      for (const r of rows) {
        await prisma.property.upsert({
          where: { id: String(r.id) },
          create: {
            id: String(r.id),
            name: String(r.name ?? ""),
            address: r.address ? String(r.address) : null,
            city: String(r.city ?? ""),
            state: String(r.state ?? ""),
            comm: Number(r.comm) || 25,
            capital: Number(r.capital) || 0,
            type: String(r.type ?? ""),
            rooms: Number(r.rooms) || 0,
            assets: (r.assets ?? []) as never,
            image_path: r.image_path ? String(r.image_path) : null,
          },
          update: {
            name: String(r.name ?? ""),
            address: r.address ? String(r.address) : null,
            city: String(r.city ?? ""),
            state: String(r.state ?? ""),
            comm: Number(r.comm) || 25,
            capital: Number(r.capital) || 0,
            type: String(r.type ?? ""),
            rooms: Number(r.rooms) || 0,
            assets: (r.assets ?? []) as never,
          },
        });
      }
      results.push({ table: "properties", processed: rows.length });
    } catch (err) {
      results.push({
        table: "properties",
        processed: 0,
        error: err instanceof Error ? err.message : "Unknown error",
      });
    }
  }

  // ---------------------------------------------------------------------------
  // Investors
  // ---------------------------------------------------------------------------
  if (Array.isArray(body.investors)) {
    try {
      const rows = (body.investors as Array<Record<string, unknown>>).filter(
        (r) => typeof r.id === "string"
      );
      for (const r of rows) {
        await prisma.investor.upsert({
          where: { id: String(r.id) },
          create: {
            id: String(r.id),
            property_id: String(r.property_id),
            name: String(r.name ?? ""),
            contact: r.contact ? String(r.contact) : null,
            email: r.email ? String(r.email) : null,
            capital: Number(r.capital) || 0,
            share_pct: Number(r.share_pct) || 0,
            notes: r.notes ? String(r.notes) : null,
          },
          update: {
            name: String(r.name ?? ""),
            contact: r.contact ? String(r.contact) : null,
            email: r.email ? String(r.email) : null,
            capital: Number(r.capital) || 0,
            share_pct: Number(r.share_pct) || 0,
            notes: r.notes ? String(r.notes) : null,
          },
        });
      }
      results.push({ table: "investors", processed: rows.length });
    } catch (err) {
      results.push({
        table: "investors",
        processed: 0,
        error: err instanceof Error ? err.message : "Unknown error",
      });
    }
  }

  // ---------------------------------------------------------------------------
  // Guests
  // ---------------------------------------------------------------------------
  if (Array.isArray(body.guests)) {
    try {
      const rows = (body.guests as Array<Record<string, unknown>>).filter(
        (r) => typeof r.id === "string"
      );
      for (const r of rows) {
        await prisma.guest.upsert({
          where: { id: String(r.id) },
          create: {
            id: String(r.id),
            name: String(r.name ?? ""),
            email: r.email ? String(r.email) : null,
            phone: r.phone ? String(r.phone) : null,
            nationality: r.nationality ? String(r.nationality) : null,
            city: r.city ? String(r.city) : null,
            notes: r.notes ? String(r.notes) : null,
          },
          update: {
            name: String(r.name ?? ""),
            email: r.email ? String(r.email) : null,
            phone: r.phone ? String(r.phone) : null,
            nationality: r.nationality ? String(r.nationality) : null,
            city: r.city ? String(r.city) : null,
            notes: r.notes ? String(r.notes) : null,
          },
        });
      }
      results.push({ table: "guests", processed: rows.length });
    } catch (err) {
      results.push({
        table: "guests",
        processed: 0,
        error: err instanceof Error ? err.message : "Unknown error",
      });
    }
  }

  // ---------------------------------------------------------------------------
  // Bookings
  // ---------------------------------------------------------------------------
  if (Array.isArray(body.bookings)) {
    try {
      const rows = (body.bookings as Array<Record<string, unknown>>).filter(
        (r) => typeof r.id === "string"
      );
      for (const r of rows) {
        await prisma.booking.upsert({
          where: { id: String(r.id) },
          create: {
            id: String(r.id),
            property_id: String(r.property_id),
            guest_id: r.guest_id ? String(r.guest_id) : null,
            check_in: new Date(String(r.check_in)),
            check_out: new Date(String(r.check_out)),
            nights: Number(r.nights) || 0,
            revenue: Number(r.revenue) || 0,
            room_amount: r.room_amount ? Number(r.room_amount) : null,
            booking_type: r.booking_type ? String(r.booking_type) : null,
            event_type: r.event_type ? String(r.event_type) : null,
            event_guests: r.event_guests ? Number(r.event_guests) : null,
            food_cost: r.food_cost ? Number(r.food_cost) : null,
            services: r.services ? String(r.services) : null,
            rating: r.rating ? Number(r.rating) : null,
            platform: r.platform ? String(r.platform) : null,
            status: String(r.status ?? "confirmed"),
            notes: r.notes ? String(r.notes) : null,
          },
          update: {
            revenue: Number(r.revenue) || 0,
            status: String(r.status ?? "confirmed"),
            notes: r.notes ? String(r.notes) : null,
          },
        });
      }
      results.push({ table: "bookings", processed: rows.length });
    } catch (err) {
      results.push({
        table: "bookings",
        processed: 0,
        error: err instanceof Error ? err.message : "Unknown error",
      });
    }
  }

  // ---------------------------------------------------------------------------
  // Daily Expenses
  // ---------------------------------------------------------------------------
  if (Array.isArray(body.daily_expenses)) {
    try {
      const rows = (body.daily_expenses as Array<Record<string, unknown>>).filter(
        (r) => typeof r.id === "string"
      );
      for (const r of rows) {
        await prisma.dailyExpense.upsert({
          where: { id: String(r.id) },
          create: {
            id: String(r.id),
            property_id: String(r.property_id),
            expense_date: new Date(String(r.expense_date)),
            category: String(r.category ?? ""),
            description: r.description ? String(r.description) : null,
            amount: Number(r.amount) || 0,
            invoice_path: r.invoice_path ? String(r.invoice_path) : null,
          },
          update: {
            category: String(r.category ?? ""),
            description: r.description ? String(r.description) : null,
            amount: Number(r.amount) || 0,
          },
        });
      }
      results.push({ table: "daily_expenses", processed: rows.length });
    } catch (err) {
      results.push({
        table: "daily_expenses",
        processed: 0,
        error: err instanceof Error ? err.message : "Unknown error",
      });
    }
  }

  // ---------------------------------------------------------------------------
  // Expenses — model removed in migration remove_expense_model; skip silently
  // ---------------------------------------------------------------------------

  // ---------------------------------------------------------------------------
  // Payouts
  // ---------------------------------------------------------------------------
  if (Array.isArray(body.payouts)) {
    try {
      const rows = (body.payouts as Array<Record<string, unknown>>).filter(
        (r) => typeof r.id === "string"
      );
      for (const r of rows) {
        await prisma.payout.upsert({
          where: { id: String(r.id) },
          create: {
            id: String(r.id),
            property_id: String(r.property_id),
            investor_id: String(r.investor_id),
            year: Number(r.year),
            month: Number(r.month),
            amount_owed: Number(r.amount_owed) || 0,
            amount_paid: r.amount_paid ? Number(r.amount_paid) : null,
            paid_on: r.paid_on ? new Date(String(r.paid_on)) : null,
            reference: r.reference ? String(r.reference) : null,
            notes: r.notes ? String(r.notes) : null,
          },
          update: {
            amount_owed: Number(r.amount_owed) || 0,
            amount_paid: r.amount_paid ? Number(r.amount_paid) : null,
            paid_on: r.paid_on ? new Date(String(r.paid_on)) : null,
            reference: r.reference ? String(r.reference) : null,
          },
        });
      }
      results.push({ table: "payouts", processed: rows.length });
    } catch (err) {
      results.push({
        table: "payouts",
        processed: 0,
        error: err instanceof Error ? err.message : "Unknown error",
      });
    }
  }

  // ---------------------------------------------------------------------------
  // Reports
  // ---------------------------------------------------------------------------
  if (Array.isArray(body.reports)) {
    try {
      const rows = (body.reports as Array<Record<string, unknown>>).filter(
        (r) => typeof r.id === "string"
      );
      for (const r of rows) {
        await prisma.report.upsert({
          where: { id: String(r.id) },
          create: {
            id: String(r.id),
            property_id: r.property_id ? String(r.property_id) : null,
            title: String(r.title ?? ""),
            period_type: String(r.period_type ?? "monthly"),
            year: Number(r.year),
            month: r.month ? Number(r.month) : null,
            data: (r.data ?? {}) as never,
          },
          update: {
            title: String(r.title ?? ""),
            data: (r.data ?? {}) as never,
          },
        });
      }
      results.push({ table: "reports", processed: rows.length });
    } catch (err) {
      results.push({
        table: "reports",
        processed: 0,
        error: err instanceof Error ? err.message : "Unknown error",
      });
    }
  }

  // ---------------------------------------------------------------------------
  // Utils Settings
  // ---------------------------------------------------------------------------
  if (Array.isArray(body.utils_settings)) {
    try {
      const rows = (body.utils_settings as Array<Record<string, unknown>>).filter(
        (r) => typeof r.key === "string"
      );
      for (const r of rows) {
        await prisma.utilsSetting.upsert({
          where: { key: String(r.key) },
          create: {
            key: String(r.key),
            value: (r.value ?? null) as never,
            description: r.description ? String(r.description) : null,
          },
          update: {
            value: (r.value ?? null) as never,
            description: r.description ? String(r.description) : null,
          },
        });
      }
      results.push({ table: "utils_settings", processed: rows.length });
    } catch (err) {
      results.push({
        table: "utils_settings",
        processed: 0,
        error: err instanceof Error ? err.message : "Unknown error",
      });
    }
  }

  const totalProcessed = results.reduce((s, r) => s + r.processed, 0);

  // Regenerate all reports from restored ops data.
  // Wrapped in try/catch — a partial restore (e.g. bookings without properties)
  // may cause regen to skip some keys. Reports will self-correct on the next write.
  try {
    await regenReports();
  } catch {
    // Non-fatal: restore succeeded, reports will regenerate on next write
  }

  return NextResponse.json({ results, total_processed: totalProcessed });
}